### ISSUE TITLE
error executing python atac-pipe.py

### ISSUE THREAD

**Issue by learner146911** [QuKunLab/ATAC-pipe#2]
got this issue when running command `python atac-pipe.py`:
 
```
Traceback (most recent call last):
  File "atac-pipe.py", line 8, in <module>
    import levenshtein
ImportError: No module named levenshtein
```
 what do you think went wrong?

**Comment by jefferyUstc** [comment]
import Levenshtein

**Comment by jefferyUstc** [comment]
> got this issue when running command `python atac-pipe.py`:
> 
> ```
> Traceback (most recent call last):
>   File "atac-pipe.py", line 8, in <module>
>     import levenshtein
> ImportError: No module named levenshtein
> ```
> what do you think went wrong?

import Levenshtein
